#############################################################################
# Makefile for building: TestDynamicManeuver
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 26 15:20:07 2024
# Project:  cut.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile cut.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I.moc -Isrc/forms_ui/headers
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/main.cpp \
		src/widgets/DrawingsBDWidget.cpp \
		src/widgets/GraphicsScene_PopupMenu.cpp \
		src/widgets/ManeuverSettingsWidget.cpp \
		src/widgets/maneuverwidget.cpp \
		src/widgets/ScaleWidget.cpp \
		src/graphics/AirObjGrItem.cpp \
		src/graphics/GraphicsEngine.cpp \
		src/graphics/GraphicsScene.cpp \
		src/graphics/Icons.cpp \
		src/graphics/MapScene.cpp \
		src/graphics/PointGraphicsItem.cpp \
		src/math/FnMath.cpp \
		src/math/Position.cpp \
		src/graphics/maneuver_gritem.cpp \
		src/graphics/AirObjRouteGraphicsItem.cpp .moc/moc_DrawingsBDWidget.cpp \
		.moc/moc_GraphicsScene_PopupMenu.cpp \
		.moc/moc_ManeuverSettingsWidget.cpp \
		.moc/moc_maneuverwidget.cpp \
		.moc/moc_ScaleWidget.cpp \
		.moc/moc_GraphicsEngine.cpp \
		.moc/moc_GraphicsScene.cpp \
		.moc/moc_PointGraphicsItem.cpp \
		.moc/moc_AirObjRouteGraphicsItem.cpp \
		qrc_resource.cpp
OBJECTS       = .obj/main.o \
		.obj/DrawingsBDWidget.o \
		.obj/GraphicsScene_PopupMenu.o \
		.obj/ManeuverSettingsWidget.o \
		.obj/maneuverwidget.o \
		.obj/ScaleWidget.o \
		.obj/AirObjGrItem.o \
		.obj/GraphicsEngine.o \
		.obj/GraphicsScene.o \
		.obj/Icons.o \
		.obj/MapScene.o \
		.obj/PointGraphicsItem.o \
		.obj/FnMath.o \
		.obj/Position.o \
		.obj/maneuver_gritem.o \
		.obj/AirObjRouteGraphicsItem.o \
		.obj/moc_DrawingsBDWidget.o \
		.obj/moc_GraphicsScene_PopupMenu.o \
		.obj/moc_ManeuverSettingsWidget.o \
		.obj/moc_maneuverwidget.o \
		.obj/moc_ScaleWidget.o \
		.obj/moc_GraphicsEngine.o \
		.obj/moc_GraphicsScene.o \
		.obj/moc_PointGraphicsItem.o \
		.obj/moc_AirObjRouteGraphicsItem.o \
		.obj/qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		cut.pro
QMAKE_TARGET  = TestDynamicManeuver
DESTDIR       = 
TARGET        = TestDynamicManeuver

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/forms_ui/headers/ui_drawingsbd_widget.h src/forms_ui/headers/ui_ManeuverSettingsWidget.h src/forms_ui/headers/ui_maneuverwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: cut.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile cut.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile cut.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/TestDynamicManeuver1.0.0 || $(MKDIR) .obj/TestDynamicManeuver1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/TestDynamicManeuver1.0.0/ && $(COPY_FILE) --parents src/widgets/DrawingsBDWidget.hpp src/widgets/GraphicsScene_PopupMenu.h src/widgets/ManeuverSettingsWidget.h src/widgets/maneuverwidget.h src/widgets/ScaleWidget.hpp src/graphics/AirObjGrItem.hpp src/graphics/GraphicsEngine.hpp src/graphics/GraphicsScene.hpp src/graphics/Icons.hpp src/graphics/MapScene.hpp src/graphics/PointGraphicsItem.hpp src/math/FnMath.hpp src/math/Position.hpp src/graphics/maneuver_gritem.h src/graphics/AirObjRouteGraphicsItem.hpp .obj/TestDynamicManeuver1.0.0/ && $(COPY_FILE) --parents src/resources/resource.qrc .obj/TestDynamicManeuver1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/widgets/DrawingsBDWidget.cpp src/widgets/GraphicsScene_PopupMenu.cpp src/widgets/ManeuverSettingsWidget.cpp src/widgets/maneuverwidget.cpp src/widgets/ScaleWidget.cpp src/graphics/AirObjGrItem.cpp src/graphics/GraphicsEngine.cpp src/graphics/GraphicsScene.cpp src/graphics/Icons.cpp src/graphics/MapScene.cpp src/graphics/PointGraphicsItem.cpp src/math/FnMath.cpp src/math/Position.cpp src/graphics/maneuver_gritem.cpp src/graphics/AirObjRouteGraphicsItem.cpp .obj/TestDynamicManeuver1.0.0/ && $(COPY_FILE) --parents src/forms_ui/drawingsbd_widget.ui src/forms_ui/ManeuverSettingsWidget.ui src/forms_ui/maneuverwidget.ui .obj/TestDynamicManeuver1.0.0/ && (cd `dirname .obj/TestDynamicManeuver1.0.0` && $(TAR) TestDynamicManeuver1.0.0.tar TestDynamicManeuver1.0.0 && $(COMPRESS) TestDynamicManeuver1.0.0.tar) && $(MOVE) `dirname .obj/TestDynamicManeuver1.0.0`/TestDynamicManeuver1.0.0.tar.gz . && $(DEL_FILE) -r .obj/TestDynamicManeuver1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_DrawingsBDWidget.cpp .moc/moc_GraphicsScene_PopupMenu.cpp .moc/moc_ManeuverSettingsWidget.cpp .moc/moc_maneuverwidget.cpp .moc/moc_ScaleWidget.cpp .moc/moc_GraphicsEngine.cpp .moc/moc_GraphicsScene.cpp .moc/moc_PointGraphicsItem.cpp .moc/moc_AirObjRouteGraphicsItem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_DrawingsBDWidget.cpp .moc/moc_GraphicsScene_PopupMenu.cpp .moc/moc_ManeuverSettingsWidget.cpp .moc/moc_maneuverwidget.cpp .moc/moc_ScaleWidget.cpp .moc/moc_GraphicsEngine.cpp .moc/moc_GraphicsScene.cpp .moc/moc_PointGraphicsItem.cpp .moc/moc_AirObjRouteGraphicsItem.cpp
.moc/moc_DrawingsBDWidget.cpp: src/forms_ui/headers/ui_drawingsbd_widget.h \
		src/graphics/GraphicsEngine.hpp \
		src/graphics/GraphicsScene.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/widgets/ScaleWidget.hpp \
		src/graphics/MapScene.hpp \
		src/graphics/Icons.hpp \
		src/graphics/FrontierGrItem.hpp \
		src/graphics/AirportGrItem.hpp \
		src/graphics/ExtabonentGrItem.hpp \
		src/widgets/DrawingsBDWidget.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/widgets/DrawingsBDWidget.hpp -o .moc/moc_DrawingsBDWidget.cpp

.moc/moc_GraphicsScene_PopupMenu.cpp: src/widgets/GraphicsScene_PopupMenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/widgets/GraphicsScene_PopupMenu.h -o .moc/moc_GraphicsScene_PopupMenu.cpp

.moc/moc_ManeuverSettingsWidget.cpp: src/forms_ui/headers/ui_ManeuverSettingsWidget.h \
		src/widgets/ManeuverSettingsWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/widgets/ManeuverSettingsWidget.h -o .moc/moc_ManeuverSettingsWidget.cpp

.moc/moc_maneuverwidget.cpp: src/forms_ui/headers/ui_maneuverwidget.h \
		src/widgets/maneuverwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/widgets/maneuverwidget.h -o .moc/moc_maneuverwidget.cpp

.moc/moc_ScaleWidget.cpp: src/graphics/MapScene.hpp \
		src/math/FnMath.hpp \
		src/graphics/Icons.hpp \
		src/widgets/ScaleWidget.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/widgets/ScaleWidget.hpp -o .moc/moc_ScaleWidget.cpp

.moc/moc_GraphicsEngine.cpp: src/graphics/GraphicsScene.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/widgets/ScaleWidget.hpp \
		src/graphics/MapScene.hpp \
		src/graphics/Icons.hpp \
		src/graphics/FrontierGrItem.hpp \
		src/graphics/AirportGrItem.hpp \
		src/graphics/ExtabonentGrItem.hpp \
		src/graphics/GraphicsEngine.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/graphics/GraphicsEngine.hpp -o .moc/moc_GraphicsEngine.cpp

.moc/moc_GraphicsScene.cpp: src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/graphics/GraphicsScene.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/graphics/GraphicsScene.hpp -o .moc/moc_GraphicsScene.cpp

.moc/moc_PointGraphicsItem.cpp: src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/graphics/PointGraphicsItem.hpp -o .moc/moc_PointGraphicsItem.cpp

.moc/moc_AirObjRouteGraphicsItem.cpp: src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/graphics/AirObjRouteGraphicsItem.hpp -o .moc/moc_AirObjRouteGraphicsItem.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: src/resources/resource.qrc \
		src/resources/icons.xml
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name resource src/resources/resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: src/forms_ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) src/forms_ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/forms_ui/headers/ui_drawingsbd_widget.h src/forms_ui/headers/ui_ManeuverSettingsWidget.h src/forms_ui/headers/ui_maneuverwidget.h
compiler_uic_clean:
	-$(DEL_FILE) src/forms_ui/headers/ui_drawingsbd_widget.h src/forms_ui/headers/ui_ManeuverSettingsWidget.h src/forms_ui/headers/ui_maneuverwidget.h
src/forms_ui/headers/ui_drawingsbd_widget.h: src/forms_ui/drawingsbd_widget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/forms_ui/drawingsbd_widget.ui -o src/forms_ui/headers/ui_drawingsbd_widget.h

src/forms_ui/headers/ui_ManeuverSettingsWidget.h: src/forms_ui/ManeuverSettingsWidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/forms_ui/ManeuverSettingsWidget.ui -o src/forms_ui/headers/ui_ManeuverSettingsWidget.h

src/forms_ui/headers/ui_maneuverwidget.h: src/forms_ui/maneuverwidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/forms_ui/maneuverwidget.ui -o src/forms_ui/headers/ui_maneuverwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

.obj/main.o: src/main.cpp src/widgets/DrawingsBDWidget.hpp \
		src/forms_ui/headers/ui_drawingsbd_widget.h \
		src/graphics/GraphicsEngine.hpp \
		src/graphics/GraphicsScene.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/widgets/ScaleWidget.hpp \
		src/graphics/MapScene.hpp \
		src/graphics/Icons.hpp \
		src/graphics/FrontierGrItem.hpp \
		src/graphics/AirportGrItem.hpp \
		src/graphics/ExtabonentGrItem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/DrawingsBDWidget.o: src/widgets/DrawingsBDWidget.cpp src/widgets/DrawingsBDWidget.hpp \
		src/forms_ui/headers/ui_drawingsbd_widget.h \
		src/graphics/GraphicsEngine.hpp \
		src/graphics/GraphicsScene.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/widgets/ScaleWidget.hpp \
		src/graphics/MapScene.hpp \
		src/graphics/Icons.hpp \
		src/graphics/FrontierGrItem.hpp \
		src/graphics/AirportGrItem.hpp \
		src/graphics/ExtabonentGrItem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/DrawingsBDWidget.o src/widgets/DrawingsBDWidget.cpp

.obj/GraphicsScene_PopupMenu.o: src/widgets/GraphicsScene_PopupMenu.cpp src/widgets/GraphicsScene_PopupMenu.h \
		src/widgets/ManeuverSettingsWidget.h \
		src/forms_ui/headers/ui_ManeuverSettingsWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GraphicsScene_PopupMenu.o src/widgets/GraphicsScene_PopupMenu.cpp

.obj/ManeuverSettingsWidget.o: src/widgets/ManeuverSettingsWidget.cpp src/widgets/ManeuverSettingsWidget.h \
		src/forms_ui/headers/ui_ManeuverSettingsWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ManeuverSettingsWidget.o src/widgets/ManeuverSettingsWidget.cpp

.obj/maneuverwidget.o: src/widgets/maneuverwidget.cpp src/widgets/maneuverwidget.h \
		src/forms_ui/headers/ui_maneuverwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/maneuverwidget.o src/widgets/maneuverwidget.cpp

.obj/ScaleWidget.o: src/widgets/ScaleWidget.cpp src/widgets/ScaleWidget.hpp \
		src/graphics/MapScene.hpp \
		src/math/FnMath.hpp \
		src/graphics/Icons.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ScaleWidget.o src/widgets/ScaleWidget.cpp

.obj/AirObjGrItem.o: src/graphics/AirObjGrItem.cpp src/graphics/AirObjGrItem.hpp \
		src/math/FnMath.hpp \
		src/math/Position.hpp \
		src/graphics/Icons.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/AirObjGrItem.o src/graphics/AirObjGrItem.cpp

.obj/GraphicsEngine.o: src/graphics/GraphicsEngine.cpp src/graphics/GraphicsEngine.hpp \
		src/graphics/GraphicsScene.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/widgets/ScaleWidget.hpp \
		src/graphics/MapScene.hpp \
		src/graphics/Icons.hpp \
		src/graphics/FrontierGrItem.hpp \
		src/graphics/AirportGrItem.hpp \
		src/graphics/ExtabonentGrItem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GraphicsEngine.o src/graphics/GraphicsEngine.cpp

.obj/GraphicsScene.o: src/graphics/GraphicsScene.cpp src/graphics/GraphicsScene.hpp \
		src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/graphics/MapScene.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GraphicsScene.o src/graphics/GraphicsScene.cpp

.obj/Icons.o: src/graphics/Icons.cpp src/graphics/Icons.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Icons.o src/graphics/Icons.cpp

.obj/MapScene.o: src/graphics/MapScene.cpp src/graphics/MapScene.hpp \
		src/math/FnMath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/MapScene.o src/graphics/MapScene.cpp

.obj/PointGraphicsItem.o: src/graphics/PointGraphicsItem.cpp src/graphics/PointGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/MapScene.hpp \
		src/widgets/GraphicsScene_PopupMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/PointGraphicsItem.o src/graphics/PointGraphicsItem.cpp

.obj/FnMath.o: src/math/FnMath.cpp src/math/FnMath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/FnMath.o src/math/FnMath.cpp

.obj/Position.o: src/math/Position.cpp src/math/Position.hpp \
		src/math/FnMath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Position.o src/math/Position.cpp

.obj/maneuver_gritem.o: src/graphics/maneuver_gritem.cpp src/graphics/maneuver_gritem.h \
		src/math/FnMath.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/maneuver_gritem.o src/graphics/maneuver_gritem.cpp

.obj/AirObjRouteGraphicsItem.o: src/graphics/AirObjRouteGraphicsItem.cpp src/graphics/AirObjRouteGraphicsItem.hpp \
		src/math/Position.hpp \
		src/math/FnMath.hpp \
		src/graphics/PointGraphicsItem.hpp \
		src/widgets/GraphicsScene_PopupMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/AirObjRouteGraphicsItem.o src/graphics/AirObjRouteGraphicsItem.cpp

.obj/moc_DrawingsBDWidget.o: .moc/moc_DrawingsBDWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_DrawingsBDWidget.o .moc/moc_DrawingsBDWidget.cpp

.obj/moc_GraphicsScene_PopupMenu.o: .moc/moc_GraphicsScene_PopupMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_GraphicsScene_PopupMenu.o .moc/moc_GraphicsScene_PopupMenu.cpp

.obj/moc_ManeuverSettingsWidget.o: .moc/moc_ManeuverSettingsWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_ManeuverSettingsWidget.o .moc/moc_ManeuverSettingsWidget.cpp

.obj/moc_maneuverwidget.o: .moc/moc_maneuverwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_maneuverwidget.o .moc/moc_maneuverwidget.cpp

.obj/moc_ScaleWidget.o: .moc/moc_ScaleWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_ScaleWidget.o .moc/moc_ScaleWidget.cpp

.obj/moc_GraphicsEngine.o: .moc/moc_GraphicsEngine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_GraphicsEngine.o .moc/moc_GraphicsEngine.cpp

.obj/moc_GraphicsScene.o: .moc/moc_GraphicsScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_GraphicsScene.o .moc/moc_GraphicsScene.cpp

.obj/moc_PointGraphicsItem.o: .moc/moc_PointGraphicsItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_PointGraphicsItem.o .moc/moc_PointGraphicsItem.cpp

.obj/moc_AirObjRouteGraphicsItem.o: .moc/moc_AirObjRouteGraphicsItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_AirObjRouteGraphicsItem.o .moc/moc_AirObjRouteGraphicsItem.cpp

.obj/qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

